#!/bin/bash 
set -e

if [ -z "${SOLR_VERSION+x}" ]
	then SOLR_VERSION=4.10.4;
fi

SOLR_HOME_DIR=${OPENSHIFT_DATA_DIR}solr
SOLR_LIB_DIR=${OPENSHIFT_DATA_DIR}lib

cd $OPENSHIFT_DATA_DIR
if [ ! -d ${SOLR_HOME_DIR} ]; then

  # Get Apache Solr
  wget -c http://archive.apache.org/dist/lucene/solr/${SOLR_VERSION}/solr-${SOLR_VERSION}.tgz && tar zxf solr-${SOLR_VERSION}.tgz;
  
  # Create Solr directory structure
  mkdir -p ${SOLR_HOME_DIR};
  mkdir -p ${SOLR_LIB_DIR};
  mkdir -p ${SOLR_LIB_DIR}/{log4j,contrib,dist};
 
  
  
  # Copy libs
  cp -R solr-$SOLR_VERSION/example/lib/ext/* solr-$SOLR_VERSION/example/resources/log4j.properties ${SOLR_LIB_DIR}/log4j;
  cp -R solr-$SOLR_VERSION/dist/* ${SOLR_LIB_DIR}/dist;
  cp -R solr-$SOLR_VERSION/contrib/* ${SOLR_LIB_DIR}/contrib;   
  
  # Copy initial configuration of Druplal
  cp -R ${OPENSHIFT_REPO_DIR}solr/* ${SOLR_HOME_DIR}
  
  # Copy collection1 and change lib directories
  cp -R solr-$SOLR_VERSION/example/solr/collection1 ${SOLR_HOME_DIR} 
  xsltproc -o solr-$SOLR_VERSION/example/solr/collection1/conf/solrconfig.xml ${OPENSHIFT_REPO_DIR}xslt/ChangeLibDir.xsl solr-$SOLR_VERSION/example/solr/collection1/conf/solrconfig.xml
  
  # Copy Solr WAR
  cp solr-$SOLR_VERSION/dist/solr-$SOLR_VERSION.war ${OPENSHIFT_HOMEDIR}/jbossews/webapps/ROOT.war
  
fi

